version: "3.8"

services:
  visualizer:
    restart: always
    image: dockersamples/visualizer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 1010:8080

  portainer:
    image: portainer/portainer:1.24.2-alpine
    restart: always
    ports:
      - 1020:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  docker-registry:
    restart: always
    image: registry:2
    ports:
      - 1030:5000
    volumes:
      - ${DEVOPS_ROOT}/devops/docker-registry/data:/var/lib/registry
      - ${DEVOPS_ROOT}/devops/docker-registry/certs:/certs
      - ${DEVOPS_ROOT}/devops/docker-registry/auth:/auth

  npm-registry:
    restart: always
    image: verdaccio/verdaccio:5.1
    ports:
      - 1040:4873
    volumes:
      - ${DEVOPS_ROOT}/devops/npm-registry/conf:/verdaccio/conf
      - ${DEVOPS_ROOT}/devops/npm-registry/plugins:/verdaccio/plugins
      - ${DEVOPS_ROOT}/devops/npm-registry/storage:/verdaccio/storage

  maven-repository:
    restart: always
    image: xetusoss/archiva:v2.2.5
    ports:
      - 1050:8080
    volumes:
      - ${DEVOPS_ROOT}/devops/maven-repository:/archiva-data