[versions]
foundation = "1.4.40"
stdlib = "0.2.0"

[libraries]
applikation-runtime = { module = "tz.co.asoft:applikation-runtime", version.ref = "foundation" }

cache-api = { module = "tz.co.asoft:cache-api", version.ref = "foundation" }
cache-browser = { module = "tz.co.asoft:cache-browser", version.ref = "foundation" }
cache-mock = { module = "tz.co.asoft:cache-mock", version.ref = "foundation" }
cache-react-native = { module = "tz.co.asoft:cache-react-native", version.ref = "foundation" }

expect-core = { module = "tz.co.asoft:expect-core", version.ref = "foundation" }
expect-coroutines = { module = "tz.co.asoft:expect-coroutines", version.ref = "foundation" }

identifier-core = { module = "tz.co.asoft:identifier-core", version.ref = "stdlib" }

kotlinx-collections-interoperable = { module = "tz.co.asoft:kotlinx-collections-interoperable", version.ref = "foundation" }
kotlinx-serialization-mapper = { module = "tz.co.asoft:kotlinx-serialization-mapper", version.ref = "foundation" }

later-core = { module = "tz.co.asoft:later-core", version.ref = "foundation" }
later-ktx = { module = "tz.co.asoft:later-ktx", version.ref = "foundation" }

live-core = { module = "tz.co.asoft:live-core", version.ref = "stdlib" }

logging-console = { module = "tz.co.asoft:logging-console", version.ref = "foundation" }

platform-core = { module = "tz.co.asoft:platform-core", version.ref = "foundation" }

reakt-core = { module = "tz.co.asoft:reakt-core", version.ref = "stdlib" }
reakt-icons = { module = "tz.co.asoft:reakt-icons", version.ref = "stdlib" }
reakt-web = { module = "tz.co.asoft:reakt-web", version.ref = "stdlib" }

viewmodel-core = { module = "tz.co.asoft:viewmodel-core", version.ref = "stdlib" }
viewmodel-react = { module = "tz.co.asoft:viewmodel-react", version.ref = "stdlib" }
viewmodel-test-expect = { module = "tz.co.asoft:viewmodel-test-expect", version.ref = "stdlib" }