name: Integration & Acceptance Testing

on:
  pull_request:
    branches: [ master-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-macos*
          key: ${{ runner.os }}-konan-
          restore-keys: ${{ runner.os }}-konan-

      - name: Making gradlew executable
        run: chmod +x ./gradlew
        working-directory: .

      - name: Download gradle
        run: ./gradlew --version

      - name: Prepare integration tests
        run: TEST_MODE=CI ./gradlew createDockerfile
        working-directory: .

      - name: Running integration tests
        run: TEST_MODE=CI ./gradlew cleanAllTest jvmTest --tests integration.*
        working-directory: .

      - name: Running acceptance tests
        run: TEST_MODE=CI HEADLESS=true ./gradlew cleanAllTest jvmTest --tests acceptance.*
        working-directory: .